### ISSUE TITLE
Undefined offset in placeholder array

### ISSUE THREAD

**Issue by roshansachan** [mirzazeyrek/wp-multiple-insert#1]
Passing following array
array(3) {
  [0]=>
  array(8) {
    ["project_id"]=>
    int(848)
    ["r_type"]=>
    string(0) ""
    ["area"]=>
    string(3) "980"
  }
  [1]=>
  array(8) {
    ["project_id"]=>
    int(848)
    ["r_type"]=>
    string(0) ""
    ["area"]=>
    string(3) "890"
  }
  [2]=>
  array(8) {
    ["project_id"]=>
    int(848)
    ["r_type"]=>
    string(0) ""
    ["area"]=>
    string(2) "90"
  }
}
results into Undefined offset: 0 
Undefined offset: 1
Undefined offset: 2 
at all lines where $place_holders[$count] .= 
is used.

**Comment by mirzazeyrek** [comment]
@roshansachan hey, nice catch. i've fixed the issue. please try again the updated version.

**Comment by roshansachan** [comment]
@mirzazeyrek Thanks for the quick fix. Keep up the good work !
