### ISSUE TITLE
Is it possible to insert array datatype

### ISSUE THREAD

**Issue by roshansachan** [mirzazeyrek/wp-multiple-insert#2]
Like we have simple string and numbers support can we have a check for array data type as well. 
I get following error when trying to insert an array:
mysqli_real_escape_string() expects parameter 2 to be string, array given in ../wp-includes/wp-db.php on line 1092

**Comment by mirzazeyrek** [comment]
What is the exact array ?

**Comment by roshansachan** [comment]
I am storing a one dimensional array in a column in db. For example name of column is referred_by and value is like [1,2,3,4] .
For now I am storing the array by serializing it which converts array to string, so it work with your code.

**Comment by mirzazeyrek** [comment]
if it works don't break it. Probably you can fork repo and modify it but currently it does the job which I exactly needed.
